### ISSUE TITLE
Source SDK Base 2013 Singleplayer Crashes on Launch After the Last Steam Update

### ISSUE THREAD

**Issue by alanedwardes** [ValveSoftware/source-sdk-2013#173]
The last 2013 base update seems to have broken the SDK base 2013 - whenever you load a map, it crashes to desktop. Even launching SDK base 2013 from steam results in a crash to desktop.

**Comment by mirkos** [comment]
I'm also, now, getting the exact same issue. My source mod crashes on startup right before it hits the main menu.

**Comment by NFMynster** [comment]
Set it to beta instead of upcoming.

**Comment by mirkos** [comment]
Hmm weird, I set it to upcoming (read a suggestion from a guy on Steam forums) and it worked. Can anyone explain to me why this is? Is there something wrong with regular version of Source SDK or what?
