### ISSUE TITLE
Engine Error - UTIL_SetModel: not precached: *2 -Possible Bug + Fix-

### ISSUE THREAD

**Issue by jessman123** [ValveSoftware/source-sdk-2013#206]
This post is based of the situation of using ep2 content. It may not apply directly to everyones situation, but it could provide incite to other fixes for similar errors.

When attempting to alter the background map in my mod, the game starts, and then begins to load the map but fails and crashes with this error : 

Engine Error-
" 41/monitor_breencast_jumbotron2 - func_monitor: UTIL_SetModel: not precached: *2 "

---

TL;DR

-First error is somewhat irrelevant but common. Mainly wanted to post more info to help source sdk peeps.

BUG: If one is making a background map for the main menu, it appears if the map file, and the key/value pair definition in chapterbackgrounds.txt, is set to "background01"  or any other map file that is used in another half-life 2 game, it fails to load due to using the games files, versus the one supplied in the mods. I feel this is because of the way its pulling content to use for the mod in the gameinfo.txt, and the half-life 2 files are dominant over the mods content. If the names are set to something that isn't included the half-life 2 files, it loads fine, and has no errors.

It may be bad config on my part, but I pulled the gameinfo.txt straight from Base 2013, so I feel it's more likely a bug. 

---

This is somewhat irrelevant..

This appears to be a common error for some people, or at least a differentiation of the error. Along with this, another error that shows its ugly face is 

" Unable to load library client " 

Based on some research and testing, I believe I now understand the problem with both of these errors. Well, partially.

I'll start with the easier one. It would conclude that my findings suggest that the error of "Unable to load library client" is purely to do with an incorrectly configured gameinfo.txt for your mod. Period. While this might be obvious to some, not everyone might understand that, besides this is primarily theoretical based on inductive reasoning.
To fix this error it would it require that you do the following:
1. Verify Source SDK, Base 2006, 2007, and 2013 are all located in your "common" folder under steamapps. Also verify that all your half-life 2 games are also in the common folder. If any of these are not, verify the integrity of your cache for all your sdk tools and games, or simply start them and it should attempt to convert them to the new .vpk format. To verify:  Open your steam library, right click on the tool or game, click properties, local files tab, verify integrity of game cache.
2. Use a gameinfo.txt that actually works with the new SteamPipe system.
   To do this, I highly recommend you use a gameinfo.txt that is already formatted for Source SDK Base 2013. You can find a gameinfo.txt in each of the halflife game folders, inside the Base 2013. As so:

C:\Program Files (x86)\Steam\steamapps\common\Source SDK Base 2013 Singleplayer\GAME NAME HERE

^ This is if your making a singleplayer mod, of course.
Realistically, I think you should be able to use any of them (hl2, episodic, or ep2, maybe even sourcetest) and simply change the " SteamAppId " to whatever ID of what game you want the mod to run for. However, each gameinfo.txt might call specifically for that games content, as I think it does, so I would use the game relevant to you. The main important part is that the format is correct. I used the " ep2 " gameinfo.txt, and left everything the same, except the game name and titles. Here is my gameinfo.txt (Without the comments) : 

```
GameInfo
{

    game                 "MOD NAME HERE"
    title                 "TITLE IN GAME FOR MOD HERE"
    title2                ""
    type                singleplayer_only

    FileSystem
    {
            SteamAppId                                420                

            SearchPaths
            {

                    game+mod                        ep2/custom/*
                    game+mod                        episodic/custom/*
                    game+mod                        hl2/custom/*

                    game+mod+mod_write+default_write_path                |gameinfo_path|.
                    gamebin                                |gameinfo_path|bin

                    game_lv                                hl2/hl2_lv.vpk
                    game+mod                        ep2/ep2_english.vpk
                    game+mod                        ep2/ep2_pak.vpk
                    game                                |all_source_engine_paths|episodic/ep1_english.vpk
                    game                                |all_source_engine_paths|episodic/ep1_pak.vpk
                    game                                |all_source_engine_paths|hl2/hl2_english.vpk
                    game                                |all_source_engine_paths|hl2/hl2_pak.vpk
                    game                                |all_source_engine_paths|hl2/hl2_textures.vpk
                    game                                |all_source_engine_paths|hl2/hl2_sound_vo_english.vpk
                    game                                |all_source_engine_paths|hl2/hl2_sound_misc.vpk
                    game                                |all_source_engine_paths|hl2/hl2_misc.vpk
                    platform                        |all_source_engine_paths|platform/platform_misc.vpk

                    game+game_write                ep2

                    gamebin                                episodic/bin

                    game                                |all_source_engine_paths|episodic
                    game                                |all_source_engine_paths|hl2
                    platform                        |all_source_engine_paths|platform
            }
    }
}
```
## During this scenario, however, there were no further changes to the game. It is recommended you do the same as a control. With these 2 steps, the game _should_ be able to boot and bring you to the menu. In my case, it did.

That ends all I have to say about the first error. The second error is more of the bug and fix I was speaking about in the title. I have deducted the precaching error is due technically to name overwrites in the pulled content. Let me explain in an example.

In my case, I was attempting to add my custom background map to the main menu. As it stood, once my gameinfo.txt was correct, if I added my custom map, the game would crash immediately upon attempt to loading. But if I removed it, or renamed it, It would load the half life 2 background map "01" , or the original that shows when there are no prior saves. Under my mods config, scripts, and my chapterbackgrounds.txt file had my first chapter labeld "background01", originally "ep2_background01". Like most people in my opinion, assuming the error is of the same nature, we simply drop the "ep2_" and leave it as "background01". We then add our map to the "maps" folder and attempt to see our masterpiece in action. Except I kept getting that pesky error. In testing, I swapped my "masterpiece" with a empty square room with nothing but a info_player_start, but if it is named "background01" it fails with a different error, but nonetheless about precaching failure. I then got curious and renamed my , lets call it "testbox", to "test". I restarted the mod, the menu game up, loaded the default half-life 2 background and was ready to go. I brought up the console and executed, "map test". 

Viola! SUCCESS! The map works! But why? Working with computers, I got the idea that there must be some sort of conflict in the content names. Doing some investigating I realized that the half-life 2 background was also named "background01". So I set my chapter1 background name to look for "test", started my mod, and It worked and loaded my testbox as the menu background. I brought the console up, and tried to load my "masterpiece" (named background01) and as I did, I noticed that it was showing 01-07 background maps. What? Where is getting that? I only have one file named that. I attempted to load it anyway. BAM. Hit with the infamous precaching error. That is when I discovered that it was failing because it was never loading my "masterpiece", it was loading the background pulled over in the content grab, defined in the gameinfo.txt.

To test this hypothesis, I renamed the map name is chapterbackground.txt to something other than background(X), X being a number such as 01-07 I think that exists hl2. I name mine "modname_back01" and then duplicated the name for the actual map file. I restarted my mod, and JUSTICE! My menu map works! It appears the content pull was conflicting with the name I had given it, and instead of loading my "masterpiece", it loaded hl2's. However, if the file and chapterbackground key/value pair name is changed, it works great!

I'm not sure really what part of the setup is to blame for the error, but I think it is related to how the gameinfo.txt pulls content over. The base is fairly new so I do not blame it for having some problems, but thankfully, I feel this is a simple one. This post is really long, the first error may be irrelevant but it is a common problem, and this post may not belong in issues, but I felt it did.

**Comment by Azzlanoid** [comment]
Thank you so much, I was so confused because I got this error but then I found this among all the other useless sites and it perfectly described my problem. Ofc I tried everything but couldnt have guessed that it was all because I named the map "background01"

**Comment by unfunny1** [comment]
can i fix this for a mod that i didnt make? im trying to play CUBE v1 i used steampipe and got that error

**Comment by TeamSpen210** [comment]
For the background map issue, that's likely because Valve patched a bunch of the maps by using a `.lmp` file to override the entity data. If such a file exists, you'll need to use `bin/vbspinfo -X0 path/to/bsp` to dump out your entity lump to override that file.
