### ISSUE TITLE
VR Mode Causes Crash on Startup

### ISSUE THREAD

**Issue by alanedwardes** [ValveSoftware/source-sdk-2013#217]
When running the latest (sp) code from this repository, both episodic and hl2 client binaries crash inside `headtrack_oculus.dll` when starting with the `-vr` command line switch.

The crash seems to be caused by a call in to `SamepleTrackingState` at the bottom of `CClientVirtualReality::ProcessCurrentTrackingState(float fGameFOV)`:

![Screenshot of crash](http://i.imgur.com/H2WNKM2.png)

A dump is available here: https://dl.dropboxusercontent.com/u/1903330/hl2-vr-headtrack-crash.dmp
## Additional Info

The -vr switch works as expected with the SDK Base Singeplayer from Steam > Tools.

I would imagine this commit is related... https://github.com/ValveSoftware/source-sdk-2013/commit/beaae8ac45a2f322a792404092d4482065bef7ef ~~but I haven't verified that yet~~ (see edit). (`Switches from headtrack.dll to sourcevr.dll` - I can't see a sourcevr.dll anywhere - is it missing from the SDK Base on Steam perhaps?)

The Source SDK Base 2013 from Steam > Tools _doesn't_ crash when using `-vr`.

I'd be more than happy to give and additional info, really want to get my mod working with the rift!

Edit: It is indeed commit https://github.com/ValveSoftware/source-sdk-2013/commit/beaae8ac45a2f322a792404092d4482065bef7ef at fault, I reverted to https://github.com/ValveSoftware/source-sdk-2013/commit/2861c3fbfc41d49627810b2d8d9bda761c3528c2, and it works fine: http://i.imgur.com/HnCYJTH.jpg

So for anyone else, any revisions before https://github.com/ValveSoftware/source-sdk-2013/commit/beaae8ac45a2f322a792404092d4482065bef7ef seem to work if you want to work on VR support.

**Comment by cmbasnett** [comment]
I've compiled the latest version of the Source SDK 2013, and I too am noticing that there is no option to turn on VR in the settings. Do you need to have a VR headset connected in order for that option to be shown?

**Comment by ChadReitsma** [comment]
@cmbasnett Yeah I'm pretty sure you do.

**Comment by ChadReitsma** [comment]
I just pulled the repo and did a compile in VS2010 Express.  

Using: Oculus Rift DK1 (with newest Runtime - from Oculus's website)
           Display mode set to:  Extended  (in Oculus Settings)


Using: SDK 2013 Multiplayer [upcoming] Binary
