### ISSUE TITLE
sp and mp variants should be in git modules

### ISSUE THREAD

**Issue by droidmonkey** [ValveSoftware/source-sdk-2013#25]
Since a mod would not utilize both code bases, either split these two branches into different repositories or set them up in the style of Qt where the modules are split into separate sub-git-repositories.

This would allow for separation of concerns between the two and not have to maintain a completely redundant pipe for mods.

Also, the "common" code should be abstracted from mp/sp. I am just not sure why there is a split to begin with, really.

**Comment by neico** [comment]
For those that don't follow me around, I've made a [group on gitlab.com](https://gitlab.com/source1) a while back which implements a proper git structure (my earlier attempt was cumbersome to look at)

This group contains a [steam-runtime](https://gitlab.com/source1/steam-runtime) project which is used for linux CI builds,

it contains a [2013 sub-group](https://gitlab.com/source1/2013) which has a [sdk-mirror](https://gitlab.com/source1/2013/sdk-mirror) repo which mirrors this one (and is therefore a great alternative for searching purposes),

a [sdk](https://gitlab.com/source1/2013/sdk) repo which contains a representation mentioned here, alas each folder split into a separate branch,

and then there's entirely new repos in the works that will fork of those branches and then facilitate Git LFS to make the repos as small and smoothly as possible, as an extra they contain a few adjustments like modifications for automated CI builds and a bit more modern gitattributes & gitignore patterns.  
Beyond that I'll probably make a `custom` branch to add customized code from the community etc.

I can't give out an ETA on when I'll be able to finish the branched out repos but I wanted to give a heads up none-the-less for those interested.

My real hope though is that valve might adopt this kind of structure (or even request to take control of said group) for any future updates as splitting the commits into branches isn't a easy thing to do (it's actually easier to commit to this existing structure then trying to split of a single commit into multiple branches) and I fear I'll have to pull out more then one leg to do that for future updates on top of the existing structure.

PS: branching out also made the commits smaller quite a bit, which should also work towards my other mentioned issue.

**Comment by droidmonkey** [comment]
Also if anyone is interested in dumping the incredibly terrible vpc build process, I had converted GoldenEye: Source's codebase to using cmake a while ago: 

https://github.com/goldeneye-source/ges-code

It's not perfect, and contains GES specifics, but it would be a great starting point for a raw sdk build using cmake.

**Comment by xXxToxicBlueDustxXx** [comment]
But here is a problem, well Cmake is a good alternative but it is very complicated since to add a new file you have to edit the cmake file and a minimal error you throw all the solution in my opinion is better VPC because it is friendly to part Of which valve works with VPC from the beginning of Source 2007 (it is known by the leak of said engine) and on cmake you must regenerate said file

**Comment by droidmonkey** [comment]
I use ucm to add directories, not individual files. You have to add files using vpc as well and it is certainly not robust in finding libs.
