### ISSUE TITLE
3D Shaded Texture Polygons view does not shade brushwork, only models.

### ISSUE THREAD

**Issue by M0tzilla** [ValveSoftware/source-sdk-2013#297]
This issue only happens in my CSGO SDK but when I select the 3D Shaded Textured Polygons for my 3D viewport it will only shade the models, world geometry / brushwork stay full bright. 

Here's what it looks like in CSGO;s Hammer: [3D Shaded Textured Polygon View](http://i.imgur.com/Dlu10yr.png)
 
The problem does not affect my L4D2 Hammer as it shades brushwork correctly as seen [here](http://i.imgur.com/rRzWbaH.png)

I've tried on a couple computers and they all are behaving the same way.

**Comment by clankill3r** [comment]
I have the issue for so many years now. It often made me quit mapping. Please fix.
In case it helps, the shading does work in the 3d flat view.

**Comment by P1x3lF3v3r** [comment]
This has also been confirmed in CSGO SDK.

**Comment by M0tzilla** [comment]
Looks like John is on a roll getting stuff closed. Hoping to get some viability on this too.

**Comment by clankill3r** [comment]
That would be so sweet. I'm working now on a add on for blender to make maps in blender for source engine. It's a lot of work but if i'm done within 10 years then I'm still faster then Valve fixing a quite important  bug :)

**Comment by Nephyrin** [comment]
Is this a regression or simply a feature that was only available in L4D2?

**Comment by M0tzilla** [comment]
If I recall correctly, it was part of hammer ever since the orange box but something along the way killed the 3d shaded viewport for hammer.

**Comment by clankill3r** [comment]
They fixed it for CS GO sdk!!! Thank you so much!

**Comment by M0tzilla** [comment]
NICE!  It appears the 3D shading is handled slightly different than before,
more dynamic maybe?... or it's just been so long since I've seen it in
action. I know it seems trivial, but this really helps as I use the 3d
viewport for most of my brush manipulation. Thanks again John!

This ticket can be closed.
