### ISSUE TITLE
to delet

### ISSUE THREAD

**Issue by stamepicmorg** [ValveSoftware/source-sdk-2013#309]
it is all right now. sorry.

**Comment by Fa11enLord** [comment]
@stamepicmorg Select Source SDK Base 2013 Singleplayer -> right mouse click -> Properties -> Beta -> Select "upcoming" in the combobox.

**Comment by stamepicmorg** [comment]
@Fa11enLord, thnx. I'll try it.

**Comment by LestaD** [comment]
Я закомментил в steam_api.h несколько строчек связанных со SteamPipe и Music

**Comment by LestaD** [comment]
При отладке отладчик ругается на эти строчки.
Я закомментил, стало всё норм. Ща дам коммит

**Comment by stamepicmorg** [comment]
@LestaD, тут дело в том, что любой мод для игры не запускается, с симптомами как первом посте. 

Такое не только на моем компьютере с моим аккаунтом, у друзей так же.

**Comment by stamepicmorg** [comment]
Bump!
