### ISSUE TITLE
STDIN console input broke on latest update

### ISSUE THREAD

**Issue by BotoX** [ValveSoftware/source-sdk-2013#338]
Hi, on todays Counter-Strike: Source update the functionality to execute commands in the client console through stdin has vanished.

I was using this functionality to make a script which reads the console output being able to execute commands on the console. (A chatbot basically, like an IRC bot with voice functionality.)

I hope that this feature can be reenabled with a startup switch or achieved through other ways.
(I guess hacking into the game would be an option, could probably get me VAC banned though.)

**Comment by joeangry** [comment]
You should report this issue [here](https://github.com/ValveSoftware/Source-1-Games) instead.

**Comment by Plagman** [comment]
That code was removed and there are no plans to bring it back.
