### ISSUE TITLE
What is "mp" and "sp" mean?

### ISSUE THREAD

**Issue by MarkkusCraft123** [ValveSoftware/source-sdk-2013#339]
Hello. I am sort of new to the Source SDK from here. This isn't really an issue, but as stated in the title, I don't know what "mp" and "sp" means here. It would be nice if it said that in the README file.

**Comment by PistonMiner** [comment]
It means MultiPlayer and SinglePlayer, you should check out the VDC page for this before asking questions here: https://developer.valvesoftware.com/wiki/Source_SDK_2013

**Comment by MarkkusCraft123** [comment]
Thanks for the quick response. I appreciate it.
