### ISSUE TITLE
[OS X] Games.mak isn't created

### ISSUE THREAD

**Issue by giogus** [ValveSoftware/source-sdk-2013#344]
I've already searched the whole valve wiki trying to solve this. I've followed every line of the tutorial but the games.mak isn't created after i build the xcode project.

<img width="562" alt="captura de tela 2015-10-13 as 19 58 10" src="https://cloud.githubusercontent.com/assets/4036914/10470604/eaa9a862-71e4-11e5-8d14-b9807a196dcf.png">

**Comment by NFMynster** [comment]
It's the creategameprojects on 80 bytes you should use.

**Comment by giogus** [comment]
@NFMynster i've already run this file, it generates a .xcodeproj, already opened the project and run but the games.mak file isn't generated!

**Comment by NFMynster** [comment]
You can ignore the third step of the tutorial, if you only want to compile the source code.

**Comment by yaakov-h** [comment]
The wiki is out of date. Source SDK 2013 on OS X no longer uses `make`, it now uses Xcode exclusively.

**Comment by giogus** [comment]
But how i use the Source Tools, like hammer editor?

**Comment by NFMynster** [comment]
They are not available for Mac. You should look into bootcamp if you want Windows on your Mac.

**Comment by giogus** [comment]
@NFMynster Thanks! I will look into bootcamp!
