### ISSUE TITLE
Can't run executables in game\bin directory

### ISSUE THREAD

**Issue by kbridge** [ValveSoftware/source-sdk-2013#346]
I build the whole SDK using VS2013. The build succeed. But when I try to run the executables, such as vbsp.exe, vrad.exe... I get an error: can't find tier0.dll and vstdlib.dll.

I find 'tier0' and 'vstdlib' directory under mp\src and sp\src. However, only a xxx_exclude.vpc file can be found under them.

Can't figure out why. Our tools depend them, but seems we exclude them from building list. So how to get these two DLLs? (Or they are actually not necessary?) Please help!

**Comment by Nephyrin** [comment]
See #347
