### ISSUE TITLE
Can't find Valve Hammer Editor in this repo.

### ISSUE THREAD

**Issue by kbridge** [ValveSoftware/source-sdk-2013#347]
From [this wiki page](https://developer.valvesoftware.com/wiki/Hammer), I learn that VHE is a component of the Source SDK. But I can't find it in this repo. Where could I find it? (the source code, I mean...) And maybe the proper way is to download it from Steam?

**Comment by PistonMiner** [comment]
The source code for the Hammer editor is not available. It is part of the Source SDK which is available on Steam, the toolset, not the source code.

**Comment by Nephyrin** [comment]
The associated tools and runtime needed for the SDK are:

- Source SDK Base 2013 Dedicated Server (for /mp)
- Source SDK Base 2013 Multiplayer (for /mp)
- Source SDK Base 2013 Singleplayer (for /sp)

Found under the 'tools' tab in steam.
