### ISSUE TITLE
VS 2013 "Could not load Project"

### ISSUE THREAD

**Issue by Callejon533** [ValveSoftware/source-sdk-2013#348]
When i open the project on vs 2013 and followed the steps in the valve wiki when i open the project it says could not load project.

Any solutions?

**Comment by mirkos** [comment]
Are you sure that you ran both of .BAT files? And if so are there any errors?

**Comment by Callejon533** [comment]
Yes and in both projects and I don't really see any errors apart from "could not load project"

**Comment by Callejon533** [comment]
Let me explain it again when I open the project in vs 2013 professional with update 5 it Shows me in the project "could not load project" and if I try to reload it it says "access denied" I run all bat files, followed what it says in the valve wiki and I get the same error I uninstalled vs 2013 and reinstalled with another version like ultimate, community and it saids the same error and yes I did try to open game project to not only the everything project. I'm the only one?

**Comment by L-EARN** [comment]
Often when you have a denied access this is because another application have an open handle to the project file.
You might want to see that using Unlocker.
Also try to make your anti-virus ignore the SDK folder.

**Comment by Callejon533** [comment]
Well I bought a new PC installed vs 2013 again and it works
