### ISSUE TITLE
Is time to fix the code valve

### ISSUE THREAD

**Issue by Callejon533** [ValveSoftware/source-sdk-2013#361]
Well before the update where the visual studio 2013 support was added then I can't compile nothing. Before I used vs 2010 and every was perfect but now with vs 2010 I get error when compiling (even if I fix the Microsoft speech sdk problem) and if I use vs 2013 I can't even open the projects. I read in the wiki that it needs to be cleaned up and I hope the code can be fixed in less than a 6 months. If anyone found a fix please respond.

**Comment by gamenew09** [comment]
Have you cleaned the projects by right-clicking on each one and pressing Clean?

**Comment by Callejon533** [comment]
Got a new PC now it works
