### ISSUE TITLE
CleanUpMap() crash @ CBaseEntityOutput::~CBaseEntityOutput()

### ISSUE THREAD

**Issue by jonnyboy0719** [ValveSoftware/source-sdk-2013#388]
I get this crash every time I run **CleanUpMap();** whenever I try to restart the round. I tried to figure out what is causing it, but It only ends up of me having a headache of not finding it.

Any suggestions that might cause this to happen would be very helpful, because It didn't happen before. And why it happens now, I got no idea, so I can't answer that question.

```
CBaseEntityOutput::~CBaseEntityOutput()
{
	CEventAction *ev = m_ActionList;
	while (ev != NULL)
	{
		CEventAction *pNext = ev->m_pNext;	// Where it crashes, line #239 @ cbase.cpp
		delete ev;
		ev = pNext;
	}
}
```

**Comment by SamVanheer** [comment]
Is this still a problem for you? When i call it it works fine in a MP mod. 
If it still happens, check the call stack and local variables. The this pointer should be valid for this destructor to work properly.

**Comment by jonnyboy0719** [comment]
This was fixed awhile ago, It was something where it was trying to kill off engine specific entities that shouldn't be killed. The "whitelist" of entities was broken for some reason, and a new clean download fixed it.
