### ISSUE TITLE
cubemaps not working

### ISSUE THREAD

**Issue by Freshz24** [ValveSoftware/source-sdk-2013#40]
I see this issue quite everywhere now, the cubemaps don't seem to work.

I can use the buildcubemaps command normally but it has no effect. Deleting the default black cubemaps from the bsp file leaves me with pink/black textured reflective floor.

Where does this issue come from?

**Comment by Nephyrin** [comment]
The beta_test branch of the Multiplayer SDK Base should now have a few engine fixes for buildcubemaps.

If you're experiencing this issue test again and let me know if there are still problems.

**Comment by 1157** [comment]
Still broke for hldms, It is adding default cubemaps, any other ones render black, If they are added,
I have not using them for 3 1/2 years ,using cheap water, texture's as a work around

**Comment by kisak-valve** [comment]
The hldms cubemap issue is being tracked at #403.
