### ISSUE TITLE
Code search is not working anymore

### ISSUE THREAD

**Issue by AdRiAnIlloO** [ValveSoftware/source-sdk-2013#405]
What is going on?

**Comment by Zaldara** [comment]
Can you give some more details?

**Comment by yupi2** [comment]
The code search on github for this repo doesn't return any results.

**Comment by AdRiAnIlloO** [comment]
Exactly, and it was working before, it stopped recently.
Note on forked repositories GitHub applies restriction on searching code.

**Comment by kem008** [comment]
Me2

**Comment by neico** [comment]
As a temporal solution, use this repo: https://gitlab.com/source1-2013/sdk
Do keep in mind that it'll most likely change soon as I'm restructuring the repo to be more git friendly. (which shouldn't affect the search tho)

**Comment by kem008** [comment]
Thanks. Now I can finally continue my work much easier now.

**Comment by Bubka3** [comment]
I asked GitHub support to reindex the code search. It appears to be working now.

@kisak-valve please close this out.

**Comment by kisak-valve** [comment]
Thanks @Bubka3, looks like it is behaving here as well, closing.
