### ISSUE TITLE
VPC customization possibility

### ISSUE THREAD

**Issue by a1batross** [ValveSoftware/source-sdk-2013#422]
Hi. 

I'm trying to adapt VPC to compile Source SDK for Android target. How should I do this "right way"?
For example, add new macro in VPC to generate Android-specific makefiles with placing binaries to lib/public/armeabi-v7a, instead of lib/public/linux32.  And name binaries as "libclient.so" or "libserver.so". 

At this time I "hacked" makefile_posix_base.mak to substitute "linux32" to "armeabi-v7a".

**Comment by Nephyrin** [comment]
The VPC source is not currently part of the SDK.  Adding a post-processing step to the generated makefiles or the base makefile to adjust the build process would probably be the way to go.

You could also try the [bear](https://github.com/rizsotto/Bear) tool to generate a more generic `compile_commands.json` database that would be more useful for a custom build setup.

**Comment by a1batross** [comment]
@Nephyrin 
It's a first thing that I did. Everything works, but looks a bit ugly and "unswitchable" between Linux and Android targets. 
It's a hell for testing code on PC first, then switching back to Android's toolchain.

Thanks for the answer and link to "bear" utility. Closing it.
