### ISSUE TITLE
NPCs are constantly taking damage from nowhere.

### ISSUE THREAD

**Issue by kaitek666** [ValveSoftware/source-sdk-2013#435]
I have a strange bug in SDK 2013 Base Singleplayer. Whenever I place any _npc_citizen_ on my map, they just keep on taking damage. It happens even if I load official HL2, EP1 or EP2 maps. First off I thought it's a problem with my mod (custom client.dll and server.dll), but even upon opening any map inside SDK Base 2013 Singleplayer itself (doubleclicking in Steam->Tools), this just keeps on happening. I removed and Installed again SDK Base 2013 SP, HL2, EP1 and EP2.. but it didn't solve my issue.

Also, it seems to be hapening with _npc_vortigaunt_ as well

What should I do? I cannot find **ANY** reference to this _weird_ bug anywhere. 

Vid (from custom map): https://www.youtube.com/watch?v=oLkEvH9Lv5U

**Comment by joeangry** [comment]
If you haven't fixed it, or someone else needs this fixed.
Copy the skill.cfg from either HL2 or EP2, that should fix it.
