### ISSUE TITLE
Alien Swarm SDK crashes on AMD Threadripper and other high core count processors

### ISSUE THREAD

**Issue by samzanemesis** [ValveSoftware/source-sdk-2013#439]
Good morning

I am the lead rendering and gameplay programmer for [City 17: The Final Stand](https://www.youtube.com/watch?v=F9jyKa-OwL4), we have some people working on the industry on this project and we plan to eventually license the engine but currently we are developing a prototype using the Alien Swarm SDK.

Currently it seems that Alien Swarm doesn't run at all on processors with high thread count like AMD's Threadripper and it's hampering development for us. Setting affinity to a lower core count for the game doesn't work either

Tier0 spews the following error:

> Out of thread ids. Decrease the number of threads or increase MAX_THREADS_SUPPORTED

We have tried to patch the tier0 DLL with reverse engineering, we found out that the error is when it fails to find a free thread ID in the range [1,32), while we managed to make the menu load by changing it to [1,128), it crashes when loading a map and doesn't generate a crashdump, there might be more uncaught references to that constant outside the block.

Could it be possible for Valve engineers to provide tier0 with a higher value for **MAX_THREADS_SUPPORTED** and provide a patch for the community? This also seems of interest to the Alien Swarm: Reactive Drop team.

**Comment by psychonic** [comment]
You would be able to fully fix by patching the dll since there are some
static arrays sized by that value. (You'd end up stomping other memory).

Your best bet is working with the Reactive Drop team as they've
successfully had Valve patch some other things small things in that
engine. I'm not sure who their contact at Valve was for that though.

-- 
Nicholas Hastings

**Comment by joeangry** [comment]
@kisak-valve any updates on this? Specifically if ASW is just not supported or any sort of word.

**Comment by samzanemesis** [comment]
Valve acknowledged this issue on another game
http://store.steampowered.com/news/37827/

**Comment by jyc** [comment]
Hello from 2020. A third party even patched the DLL: https://steamcommunity.com/app/563560/discussions/2/1693785669858241515/?ctp=2

Who can we contact to get this fixed? @kisak-valve

**Comment by samzanemesis** [comment]
I think they fixed this a while back
