### ISSUE TITLE
fatal error C1083: Cannot open include file: 'wtypes.h': No such file or directory

### ISSUE THREAD

**Issue by MonstahGames** [ValveSoftware/source-sdk-2013#444]
When trying to compile a basic Half Life 2 mod, I get the error: fatal error C1083: Cannot open include file: 'wtypes.h': No such file or directory. Any Ideas? I'm running Visual Studio 2017. (at first it didn't work on VS2017, but i changed a registry key to make it work).

**Comment by kennyrkun** [comment]
Properties → General → Target Platform Version → change to 8.1
