### ISSUE TITLE
Secobmod Crashes when map is loaded

### ISSUE THREAD

**Issue by lun4rD35p4ir** [ValveSoftware/source-sdk-2013#446]
The Co-Op base mod Secobmod: https://developer.valvesoftware.com/wiki/Co-Operative_Base_(Mod) crashes when loading any map. Setting "maxplayers" to 1 fixes the issue. I believe this happens with Tony Sergi's MP animation fix: https://github.com/tonysergi/source-sdk-2013 any fix for this?

**Comment by danksteviee** [comment]
https://gist.github.com/danksteviee/34367d9208e2dade194562e680697305 No I don't have a minidump nor CrashID on the mod because it doesn't generate.

**Comment by NicolasDe** [comment]
If you have an issue with some specific mod, report it to the creator of the mod...
If you are trying to find why and where it crashes, run the mod from the visual studio.

**Comment by PretzelCA** [comment]
SecobMod is crashing because it uses an older version of the SDK. If you want to run SecobMod, either use the previous beta branch or update it.

**Comment by lun4rD35p4ir** [comment]
Uh I already know that. This is a old issue.
