### ISSUE TITLE
Predicted sequences problem.

### ISSUE THREAD

**Issue by Mince228** [ValveSoftware/source-sdk-2013#447]
So I've been trying to make the hl2mp player animations nicely in sync with both client and the server by predicting them. After 'implementing' the SetAnimation code from CHL2MP_Player without errors into the client side of the class the system fires up but the client always has its m_nSequence set to 0 and I cant seem to find the reason for why its happening. The server seems to have normal sequence numbers but the client always outputs zeros when tested. The player model appears to be in the T-Pose most of the time but seems like its trying to correct itself towards some kind of animation, perhaps from the server value.

If anyone has any experience with this or perhaps some helpful info it would be appreciated.

**Comment by azuisleet** [comment]
The HL2MP implementation should actually be based on CMultiPlayerAnimState instead. The SetAnimation function is a red herring, as CMultiPlayerAnimState will reset the sequence anyway. 

There's a quick overview on the wiki: https://developer.valvesoftware.com/wiki/M_PlayerAnimState

You can also diagnose issues with anim_showstate 1

**Comment by Mince228** [comment]
Well I tried "implementing" CMultiPlayerAnimState but its giving me some errors: [https://imgur.com/a/z3iF2](url)
CBasePlayer for example seems to be declared inside this header file but it doesnt seem to want to recognise it along with some others. If you tried implementing this animstate did you run into the same problems?

**Comment by Mince228** [comment]
Got it fixed based on code from Tony Sergi's hub page. 

Closing
