### ISSUE TITLE
Missing Source SDK 2007 files

### ISSUE THREAD

**Issue by der-p0l** [ValveSoftware/source-sdk-2013#451]
Hi.
I recently started modifying the menu and the panels of HL2 Episodic. I managed to modify pretty much everything, but there is one panel that I can't: the "InlineEditPanel" that appears when changing a key in the keyboard options. I changed every color of sourcescheme.res but that panel doesn't change.
So I found that the color of that panel is not defined in Source SDK 2013, but in [Source SDK 2007](https://github.com/csnxs/source-2007). I also noticed that a lot of folders are missing too (could be because of deprecated code, I didn't explore too much about it), and specifically the "gameui" folder that I was looking for. In that folder is also defined the "OpenFooBarDialog" that can be used in gamemenu.res, that can be handy to me.
Is there any workaround in Source 2013, or do I have to copy the files/folders from Source 2007? And in the last case, how can I do that without messing with Source 2013 and the Steam Pipe update?
Thank you.

**Comment by TeamSpen210** [comment]
Source 2007 is actually a leaked copy of code, including many things that weren't intended to be accessible (for example the code for Hammer, Portal 1 and HLMV).

**Comment by der-p0l** [comment]
Oh, didn't know that. So is there something I can do to achieve the same results (in this case change the color of InlineEditPanel) without that code?

**Comment by neico** [comment]
First of, Source2007 per se isn't leaked, the repo you linked to very much is though, the most you should and can in fact is look at how the engine ticks and try to bend it your way.  
But using parts of anything that isn't in this source2013 repo can be considered illegal and valve might or might not take legal actions against you for doing so.

With that out of the way: the GameUI code was released to the public with the Alien Swarm SDK, which is a fork related to the L4D engine branch.  
There are community attempts to merge that into source2013, but I didn't follow those so you'd need to dig around those yourself.  
Another approach is to base your mod entirely of the Alien Swarm code, or to grab a community project that aims to merge the best of both worlds.

In any case, a quick search revealed this: https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/vgui2/vgui_controls/KeyBoardEditorDialog.cpp#L91  
I assume this is what you are looking for?

**Comment by der-p0l** [comment]
Thanks neico.
I assumed I can use that repo for reference and understanding, but not use it directly.

I didn't know of the Alien Swarm SDK and that it was related with the L4D branch. Much less did I know about the community leaded projects. Thanks for clearing that up.

Lastly, I actually found the KeyBoardEditorDialog.cpp when I was looking for keyboard options. But that file is for the keyboard options used when launching the game with "-tools -nop4"; that "InlineEditPanel" is pretty much the same used in the in-game keyboard options, but in this case for the tools.

Thank you again.
