### ISSUE TITLE
How to compile server plugins on Linux?

### ISSUE THREAD

**Issue by 132ikl** [ValveSoftware/source-sdk-2013#460]
I'm trying to figure out how to compile server plugins on Linux according to [this wiki page](https://developer.valvesoftware.com/wiki/Server_plugins), you should edit the Makefile.plugin in src/linux_sdk/. The problem is that neither Makefile.plugin nor linux_sdk exist anywhere, even after compiling everything. Am I missing something here?

**Comment by neico** [comment]
That wiki page is for pre-source2013, see [this](https://developer.valvesoftware.com/wiki/Source_SDK_2013#Source_SDK_2013_on_Linux)

**Comment by 132ikl** [comment]
Thanks, I did of exploring and was able to compile

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
