### ISSUE TITLE
Unable to launch hl2.exe successfully

### ISSUE THREAD

**Issue by BerntA** [ValveSoftware/source-sdk-2013#475]
Recently I've had a lot of trouble launching hl2.exe for some standalone Source SDK 2013 based mods, if I rename the .exe to anything but hl2 it will work fine. Otherwise hl2.exe will hang in task manager together with rundll32.exe, rundll32.exe will take up all my CPU, raise temps to 70 degrees even.

When I renamed the .exe to something else I noticed that the game created a new executable hl2.exe, when I closed the game? Perhaps this is why I can't launch hl2.exe in the first place, either way I have no idea what is going on here.

![hl2issue1](https://user-images.githubusercontent.com/10424971/59777210-84207900-92b4-11e9-8869-f8846b6ec4d3.jpg)
![hl2issue2](https://user-images.githubusercontent.com/10424971/59777211-84207900-92b4-11e9-9517-4d9137742cae.jpg)

**Comment by joeangry** [comment]
Try validating the cache for your games.

**Comment by BerntA** [comment]
Some of these games are my own, so nope, no luck there.
Apparently it even happens to other non-steam games. Verified my windows files, nothing out of the ordinary. Did a full scan for viruses/malware, nothing... I guess my PC is just on crack at the moment.
