### ISSUE TITLE
Is it possible to get very old version of Source SDK?

### ISSUE THREAD

**Issue by tjd2** [ValveSoftware/source-sdk-2013#487]

**Comment by Meerjel01** [comment]
"Half-Life 2 on the original Xbox" Was something I focused on but never really was competent to get somewhere with. Did I start your search or did someone else get you to it? I'm interested to know if I even did start something good for someone.

This is an old post so I guess you've gotten what you wanted right?

**Comment by tjd2** [comment]
> "Half-Life 2 on the original Xbox" Was something I focused on but never really was competent to get somewhere with. Did I start your search or did someone else get you to it? I'm interested to know if I even did start something good for someone.
> 
> This is an old post so I guess you've gotten what you wanted right?

We've been able to get old SDK versions, but it wasn't of much help. Majority of the HL2X code was removed in them.
We have got very small discord server for it: https://discord.gg/9W5qDdCMDc
