### ISSUE TITLE
HL2MP_Chat_All

### ISSUE THREAD

**Issue by typicalname0** [ValveSoftware/source-sdk-2013#497]
When I type in a message, all I see is "HL2MP_Chat_All". I've looked all over google but I havent found any solutions yet.

**Comment by scorpius2k1** [comment]
Copy the chat entries from the hl2mp_english.txt file into yourmod_english.txt

**Comment by typicalname0** [comment]
I've done that, but all it says in the console is something about non unicode captions.

**Comment by typicalname0** [comment]
never mind, for some reason it works now. thanks!
