### ISSUE TITLE
rewrite to rust

### ISSUE THREAD

**Issue by KumarGanesha1996** [ValveSoftware/source-sdk-2013#511]
hi kind sirs... rewrite to rust..... so it's safe and moral.

rust has:
- zero-cost abstractions
- move semantics
- guaranteed memory safety
- threads without data races
- trait-based generics
- pattern matching
- type inference
- minimal runtime
- efficient C bindings

best regards, Kumar

@JoeLudwig @jorgenpt @sortie @narendraumate @alanedwardes @bruced-valve @psychonic @plesiecki @mikesart @jstasiak @neico @Nephyrin

**Comment by micwoj92** [comment]
Rewrite it yourself noob.

**Comment by kisak-valve** [comment]
Hello @KumarGanesha1996, this is an unrealistic request to make for an older code base.

**Comment by boxandrocks** [comment]
lol

**Comment by gdianaty** [comment]
We could port it to C# for the sake of JavaScript.

**Comment by kisak-valve** [comment]
I don't usually lock issues, however, this issue report is an invitation to continuously create noise on the issue tracker for no benefit. Please use another medium to make your porting jokes.
