### ISSUE TITLE
FLT_MIN from cfloat is positive value

### ISSUE THREAD

**Issue by Karaulov2021** [ValveSoftware/source-sdk-2013#518]
https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/sp/src/utils/vrad/vrad_dispcoll.cpp#L1017

Bad valve developers?)))

**Comment by Karaulov2021** [comment]
Using FLT_MIN is very big mistake of newbie coders, in cfloat FLT_MIN = MIN **POSITIVE** FLOAT

**Comment by kisak-valve** [comment]
Hello karaulov, you've repeatedly abused Valve's issue trackers over a sustained period of time and created account after account to bypass the ban. You are not welcome here.
