### ISSUE TITLE
Valve, please fix (Counter-Strike: Source)

### ISSUE THREAD

**Issue by Smesh292** [ValveSoftware/source-sdk-2013#526]
It would not be superfluous to add a cvar which allows you to switch the physics of ragdolls between 2007 SDK or 4.
1. Fix prediction (ragdoll fly from death cam).
2. Fix float tick count (map going lag in few hours).
3. Add back v34 shader.
4. Remove fixedConstraits code block from ragdolls.
5. Allow force rates, interpolation from server.
Thank you for understanding.

**Comment by kisak-valve** [comment]
Hello @Smesh292, in general, multi-issue issue reports are bad for any issue tracker. Issues with Counter-Strike: Source should be evaluated separately, one issue per issue report on the [Source-1-Games](https://github.com/ValveSoftware/Source-1-Gamesa) issue tracker. Feel free to search that issue tracker for existing issues and open new issue reports for each of those issues if they don't already exist.
