### ISSUE TITLE
GetFreeDiskSpace(const

### ISSUE THREAD

**Issue by ctvthrf** [ValveSoftware/source-sdk-2013#535]
https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/public/vgui/ISystem.h#L100

**Comment by Kefta** [comment]
Yep that's indeed a method.

**Comment by ctvthrf** [comment]
> Yep that's indeed a method.


Good.
