### ISSUE TITLE
GetAbsVelocity()

### ISSUE THREAD

**Issue by ctvthrf** [ValveSoftware/source-sdk-2013#536]
https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/public/game/server/ientityinfo.h#L68

**Comment by kisak-valve** [comment]
Hello @ctvthrf, highlighting random single lines of code over multiple issue reports without giving any additional information isn't coherent feedback and an abuse of this issue tracker. You've been given a 24 hour timeout.
