### ISSUE TITLE
Bring updates from Half-Life 2/Half-Life 2: Deathmatch to Source SDK 2013

### ISSUE THREAD

**Issue by weaponcubemap** [ValveSoftware/source-sdk-2013#541]
Would be good if Source SDK 2013 will be updated with updates from Half-Life 2/Half-Life 2: Deathmatch, for example SteamDeck, or fixes for various bugs like NPCs not blinking, and etc.

**Comment by kisak-valve** [comment]
Hello @weaponcubemap, this feature request is already being tracked at #540. Closing as a duplicate.

**Comment by weaponcubemap** [comment]
Hello, I don't care about "duplicates", I only want Source SDK 2013 updated, that's all. Mostly because it wasn't updated since 2015 lol

**Comment by Kefta** [comment]
Just give it up and whip out IDA.

**Comment by weaponcubemap** [comment]
> Just give it up and whip out IDA.

to use IDA, you need skills...
