### ISSUE TITLE
Behavior of "cc_captiontrace" does not match documentation when set to "2"

### ISSUE THREAD

**Issue by lunalucadou** [ValveSoftware/source-sdk-2013#545]
Per https://developer.valvesoftware.com/wiki/Console_Command_List#Commands_starting_with_letter_.22C.22 the behavior of `cc_captiontrace` should be:

> Show missing closecaptions: (0 = no, 1 = devconsole, 2 = show in HUD)

However, in practice, missing captions are only printed to the console.

According to an [archived version of the wiki](http://web.archive.org/web/20060207015753/http://developer.valvesoftware.com/wiki/Console_Command_List), this behavior is not new: it was specified in the wiki all the way back in 2006.

In Source SDK 2013, this bug is present in at least two places:

* https://github.com/ValveSoftware/source-sdk-2013/blob/master/sp/src/game/client/hud_closecaption.cpp#L1468
* https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/game/client/hud_closecaption.cpp#L1469

There is likely a buggy input validation check prior to this since `cc_captiontrace 2` should cause the initial `<2` check to fail and print no missing caption errors, but in any case, even if there was no input validation error to begin with, there is no logic to print missing caption errors to the HUD. I searched this repo for `cc_captiontrace` and those were the only two results, so I expect this bug also involves some upstream code not present in the SDK.

Outside the Source SDK 2013, this bug is also present in Half-Life 2, HL2 Episode 1, and HL2 Episode 2, so this bug appears to have been around for some time. It is also present in Black Mesa, which (according to one of the Crowbar Collective team members) uses a modified version of the TF2 SDK.

I understand this is a very old codebase and this is a very obscure issue, but I have been documenting a lot of caption issues in Black Mesa, and this being fixed would make my life a lot easier since I wouldn't have to open the console to figure out if a caption didn't trigger or if a sound just doesn't have an associated caption.

**Comment by lunalucadou** [comment]
I have just confirmed this is not just a bug, but a regression.

Using Half-Life 2 Old Engine (from SourceRuns), which uses Source SDK 2006, I found that `cc_captiontrace 2` used to work as described:

![image](https://user-images.githubusercontent.com/22415965/175780540-9c9b1e30-ca71-4168-8aa4-734d81608723.png)

![image](https://user-images.githubusercontent.com/22415965/175780544-6abea478-5db8-4951-84d5-1de57abddcb6.png)

This behavior would be quite useful for my Black Mesa captioning work.

**Comment by kisak-valve** [comment]
Hello @lunalucadou, there's no real value in duplicating the same information over multiple issue trackers. Closing in favor of https://github.com/ValveSoftware/Source-1-Games/issues/3946.

**Comment by weaponcubemap** [comment]
Nobody cares about duplicates, people want to get shit fixed...

**Comment by Kefta** [comment]
I care, thank you for closing this duplicate.
