### ISSUE TITLE
Source Sdk Don't Have Npc Animations.

### ISSUE THREAD

**Issue by HelloMan12345** [ValveSoftware/source-sdk-2013#546]
Title. Please Help!

**Comment by Kefta** [comment]
The SDK doesn't contain anim/model files, you can get these from any Source game's VPK.

**Comment by HelloMan12345** [comment]
but where i can find a animations file form half life 2 ?

**Comment by Kefta** [comment]
In HL2's misc vpk's models folder, you will find <npc_name>_animations.mdl and <npc_name>_animations.ani for each NPC.

**Comment by HelloMan12345** [comment]
but i copied vpk files to custom folder in my mod folder, but still don't work

**Comment by HelloMan12345** [comment]
but i have vpk files in custom folder of my mod. but still not work

**Comment by HelloMan12345** [comment]
anyone know how to fix this ?
