### ISSUE TITLE
npcs die in one hit

### ISSUE THREAD

**Issue by breakdowngamesYT** [ValveSoftware/source-sdk-2013#547]
read title also for all weapons crowbar pistol shotgun smg all of then just one hit

**Comment by Kefta** [comment]
Like your other two issues, you've provided no info.

**Comment by breakdowngamesYT** [comment]
what info do u nead its self explanitory?

**Comment by breakdowngamesYT** [comment]
it's on a freshly compiled version of source SDK 2013 on visual studio 2013 with mcf installed and i get these errors all NPCs die in one hit and this happens for all weapons even NPCs fighting I've tried raising the health in hammer and lowering weapon damage and changing the difficulty
