### ISSUE TITLE
i cant break crates or props or anything destructable

### ISSUE THREAD

**Issue by breakdowngamesYT** [ValveSoftware/source-sdk-2013#548]
self explanitory

**Comment by Kefta** [comment]
It's not - you've given no info on if this is a mod or what the entity type is.

**Comment by breakdowngamesYT** [comment]
i compiled the source code with the steps on the vaulve devoloper wiki and it has thees three errors and entity type all wooden crats and vents the stuff thats destructable

**Comment by breakdowngamesYT** [comment]
crates*
