### ISSUE TITLE
Source SDK Model browser no GUI

### ISSUE THREAD

**Issue by 1157** [ValveSoftware/source-sdk-2013#555]
Hammer 4.1 Build 9008 no GUI for world models only folder's 
![Model_browser](https://user-images.githubusercontent.com/5712715/188328207-4796d3d7-f8e8-48ed-ac72-c39cc4654574.png)

**Comment by mutezero** [comment]
@1157 do you have "Use VGUI model browser" checked at the options?
![image](https://user-images.githubusercontent.com/13403210/188392710-9d90aa75-0b39-461c-9a0f-7b3287fc08d3.png)

**Comment by 1157** [comment]
That was it. after the hammer update i guess the default is  "unchecked". maybe better check the other settings too.
Thanks
