### ISSUE TITLE
increase entity limit and other limits like, models, brushes like gmod

### ISSUE THREAD

**Issue by Unusuario2** [ValveSoftware/source-sdk-2013#573]

**Comment by JaoN64dev** [comment]
Hello, i dont understand your question very welll but i think you are asking about how you can add stuff or change. Well you check [https://developer.valvesoftware.com/wiki/Main_Page](url) for stuff like that, or ask question at the subreddit r/SourceEngine 

Thanks and have fun modding! :D

**Comment by Unusuario2** [comment]
Hi Jao what i am asking is in source sdk 2013 increase the bsp limits, like brushes, models and entites:
https://developer.valvesoftware.com/wiki/Entity_limit it would be very nice to increased to al least 8192 entities (4096 editcs and 4096 client or server side)
https://developer.valvesoftware.com/wiki/Brush : it would be also very nice to increase the brush limit 8192 to 16.384
And finaly the displacemnt 2048 to 4096 or 8192 if posible.

These changes need to be done in the ENGINE not this public SDK

**Comment by JaoN64dev** [comment]
i am sorry, but i cant help with that :(
