### ISSUE TITLE
[enhancement] Native x86_64

### ISSUE THREAD

**Issue by GuestSneezeOSDev** [ValveSoftware/source-sdk-2013#601]
Self-explainable, I don't have to explain anything here

**Comment by kisak-valve** [comment]
Hello @GuestSneezeOSDev, this issue is already being tracked at #481 / #574. Closing as a duplicate.

**Comment by GuestSneezeOSDev** [comment]
> Hello @GuestSneezeOSDev, this issue is already being tracked at #481 / #574. Closing as a duplicate.

alright
