### ISSUE TITLE
VPC error: "Unable to find RegKey for .vcproj files in solutions"

### ISSUE THREAD

**Issue by Artfunkel** [ValveSoftware/source-sdk-2013#72]
I get this when running creategameprojects.bat:

```
C:\valve\source2013\mp\src>devtools\bin\vpc.exe /hl2mp +game /mksln games.sln
VPC - Valve Project Creator For Visual Studio, Xbox 360, PlayStation 3 (Build: Jun  5 2013 15:27:08)
(C) Copyright 1996-2010, Valve Corporation, All rights reserved.

Source Path: C:\valve\source2013\mp\src
Target Platform: win32
Generating for Visual Studio 2010.

Valid: 'client_hl2mp.vcxproj' Passes CRC Checks.

Valid: 'mathlib.vcxproj' Passes CRC Checks.

Valid: 'server_hl2mp.vcxproj' Passes CRC Checks.

Valid: 'tier1.vcxproj' Passes CRC Checks.

Valid: 'vgui_controls.vcxproj' Passes CRC Checks.

Building partial dependency set (libs only)........


Writing solution file C:\valve\source2013\mp\src\games.sln.

ERROR: Unable to find RegKey for .vcproj files in solutions.
```

I have these VS products installed:
- Visual C++ Express 2010
- Visual C# Express 2010
- Visual Studio Express 2013 Preview

...all of which are from the `vcxproj` era, so it's not surprising that `vcproj` isn't in my registry.

**Comment by RaTcHeT302** [comment]
This issue persists on Visual Studio 2015, do I really hate to install VS2013 just for this?

**Comment by WeAthFoLD** [comment]
I'm using Visual Studio 2015 and gets the same error.

**Comment by rlabrecque** [comment]
Yes, Visual Studio 2013 is required.

**Comment by ikeExternal** [comment]
VS 2013 is required to be used?

**Comment by rlabrecque** [comment]
Yes, Visual Studio 2013 is required.

**Comment by JonTerp** [comment]
For anyone looking up this error while trying to get this working on Visual Studio 2017:

As stated above, add the following registry keys if they don't already exist:
`HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\VisualStudio\10.0\Projects\{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}`

Add string key 'DefaultProjectExtension' and set the data to 'vcproj' and your sln file should generate without issue!

**Comment by jtrent238** [comment]
Yes @JonTerp 's [#issuecomment-326633328](#issuecomment-326633328) Worked!

**Comment by stevefan1999-personal** [comment]
> 
> 
> For anyone looking up this error while trying to get this working on Visual Studio 2017:
> 
> As stated above, add the following registry keys if they don't already exist:
> `HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\VisualStudio\10.0\Projects\{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}`
> 
> Add string key 'DefaultProjectExtension' and set the data to 'vcproj' and your sln file should generate without issue!

Based on your solution, you can try this little bastard if you're desperate:

```reg
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\VisualStudio\10.0\Projects\{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}]
"DefaultProjectExtension"="vcproj"
```
Save the snippet as a .reg file and run it.

**Comment by jean-knapp** [comment]
This solves the issues for 64-bit systems. What about for 32-bit systems?

**Comment by jean-knapp** [comment]
> For anyone looking up this error while trying to get this working on Visual Studio 2017:
> 
> As stated above, add the following registry keys if they don't already exist: `HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\VisualStudio\10.0\Projects\{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}`
> 
> Add string key 'DefaultProjectExtension' and set the data to 'vcproj' and your sln file should generate without issue!

This is not entirely right because not every Windows user has that registry path. Instead of using `HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node`, you should use `/reg:32`

Source: [https://serverfault.com/questions/996626/registry-keys-are-getting-imported-under-hkey-local-machine-software-wow6432node](url)

This also means this is not entirely correct:

> > For anyone looking up this error while trying to get this working on Visual Studio 2017:
> > As stated above, add the following registry keys if they don't already exist:
> > `HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\VisualStudio\10.0\Projects\{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}`
> > Add string key 'DefaultProjectExtension' and set the data to 'vcproj' and your sln file should generate without issue!
> 
> Based on your solution, you can try this little bastard if you're desperate:
> 
> ```reg
> Windows Registry Editor Version 5.00
> 
> [HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\VisualStudio\10.0\Projects\{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}]
> "DefaultProjectExtension"="vcproj"
> ```
> 
> Save the snippet as a .reg file and run it.

since if a user has the path `HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\WOW6432Node\` in registry, this .reg file won`t do anything.

In C#, one piece of code I used in XBLAH's Modding Tool that successfully wrote the correct registry was this:

```csharp
private void SetVcProjKey()
{ 
    const string keyPath = @"SOFTWARE\Microsoft\VisualStudio\10.0\Projects\{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}";
    const string valueName = "DefaultProjectExtension";
    const string valueData = "vcproj";

    try
    {
        RegistryKey registryKey = RegistryKey.OpenBaseKey(RegistryHive.LocalMachine, RegistryView.Registry32).OpenSubKey(keyPath, true);

        if (registryKey == null)
        {
            // If the key doesn't exist, create it
            registryKey = RegistryKey.OpenBaseKey(RegistryHive.LocalMachine, RegistryView.Registry32).CreateSubKey(keyPath, RegistryKeyPermissionCheck.ReadWriteSubTree);
        }

        // Set the registry value
        registryKey.SetValue(valueName, valueData, RegistryValueKind.String);
    }
    catch (Exception ex)
    {
        MessageBox.Show("Error setting registry key: " + ex.Message);
    }
}
```
